trigger:
- master
- develop

variables:
  rootDir: 'msa-p1'
  buildDir: '$(rootDir)/build'
  NASA_API_KEY: 'hu3iK9f8MJm2OTdFVTFvwkGTYyTWRUXWXE6UN5Rb'

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: CmdLine@2 
  inputs: 
    script: 'echo REACT_APP_API_KEY=$(NASA_API_KEY) > $(rootDir）/.env' 
  displayName: 'Setting environment variables'
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd $(rootDir)
    npm install
    npm run build
    cd ..
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(buildDir)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'